server:
  port: 0

spring:
  data:
    mongodb:
      uri: mongodb+srv://harshani:nima97@harshani-mongodb-cluste.nb1u3jo.mongodb.net/translation-service?retryWrites=true&w=majority

  application:
    name: translation-service
  config:
    import: configserver:http://localhost:9296

#eureka:
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

#  instance:
#    hostname: localhost


logging:
  pattern:
    level: "%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]"