server:
  port: 8080

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/dictionary-service
    username: root
    password: root

  application:
    name: dictionary-service

  eureka:
    client:
      service-url:
        defaultZone: http://localhost:8761/eureka
#
#    instance:
#      hostname: localhost


#eureka:
#  client:
#    service-url:
#      defaultZone: http://host.docker.internal:8761/eureka